version = 0.1
[default.deploy.parameters]
stack_name = "test-aws-lambda-starter"
resolve_s3 = true
s3_prefix = "test-aws-lambda-starter"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev\""
image_repositories = []
